### ISSUE TITLE
[3.5.0-pre] Key not found exception when removing the same entity multiple times

### ISSUE THREAD

**Issue by g-jozsef** [sebas77/Svelto.ECS#122]
The following error is thrown when removing the same entity twice
```
    void Test()
    {
        var simpleSubmissionEntityViewScheduler = new SimpleEntitiesSubmissionScheduler();
        var enginesRoot = new EnginesRoot(simpleSubmissionEntityViewScheduler);

        var entityFactory = enginesRoot.GenerateEntityFactory();
        var entityFunctions = enginesRoot.GenerateEntityFunctions();

        var r = entityFactory.BuildEntity<EntityDescriptor>(2, BuildGroup);
        simpleSubmissionEntityViewScheduler.SubmitEntities();
        entityFunctions.RemoveEntity<EntityDescriptor>(r.EGID);
        entityFunctions.RemoveEntity<EntityDescriptor>(r.EGID);
        simpleSubmissionEntityViewScheduler.SubmitEntities();
    }


    record struct ComponentA(uint A1) : IEntityComponent;

    sealed class EntityDescriptor : GenericEntityDescriptor<ComponentA> { }
```
```
Svelto.DataStructures.SveltoDictionaryException: Key not found
   at Svelto.ECS.EnginesRoot.RemoveEntities(FasterDictionary`2 removeOperations, FasterList`1 entitiesRemoved, EnginesRoot enginesRoot)
   at Svelto.ECS.EntitiesOperations.ExecuteRemoveAndSwappingOperations(Action`3 swapEntities, Action`3 removeEntities, Action`2 removeGroup, Action`3 swapGroup, EnginesRoot enginesRoot)
   at Svelto.ECS.EnginesRoot.EntitiesSubmitter.SubmitEntities()
   at Svelto.ECS.Schedulers.SimpleEntitiesSubmissionScheduler.SubmitEntities()
   at AmmoTest.ECS.MultipleRemoveTests.ShouldNotThrowForMultipleRemove() in E:\projects\akrogames\ammo\ammo-server\tests\AmmoTest\ECS\MultipleRemoveTests.cs:line 51
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

I also debugged it and the issue is probably that 

https://github.com/sebas77/Svelto.ECS/blob/bc53d38dcfc07ca3237ffa701f9d979cc4249441/com.sebaslab.svelto.ecs/Core/EnginesRoot.Submission.cs#L59
calls into an entitylocator remove

https://github.com/sebas77/Svelto.ECS/blob/bc53d38dcfc07ca3237ffa701f9d979cc4249441/com.sebaslab.svelto.ecs/Core/EntityReference/EnginesRoot.LocatorMap.cs#L100

and it fails here:
https://github.com/sebas77/Svelto.ECS/blob/bc53d38dcfc07ca3237ffa701f9d979cc4249441/com.sebaslab.svelto.ecs/Core/EntityReference/EnginesRoot.LocatorMap.cs#L115

the egidToReference does not contain the egid that we're removing the second time

**Comment by sebas77** [comment]
ok fixed thanks
